
proxy-groups:
  # ä¸»è¦ç­–ç•¥ç»„
  - name: ğŸš€ ä¸‡é‡‘æ²¹
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨ä¼˜é€‰
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ¡ å®¶å®½èŠ‚ç‚¹
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº

  # åµŒå¥—ç­–ç•¥ç»„
  - name: ğŸ¤– AIå¹³å°
    type: select
    proxies:
      - ğŸ’¬ AIèŠ‚ç‚¹
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸ¡ å®¶å®½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº

  - name: ğŸ“± Talkatone
    type: select
    proxies:
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸ¡ å®¶å®½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº

  - name: ğŸ˜ è™šæ‹Ÿå¡æœåŠ¡
    type: select
    proxies:
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸ¡ å®¶å®½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº

  - name: ã‰† å­¦æ ¡æœåŠ¡
    type: select
    proxies:
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸ¡ å®¶å®½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº

  - name: ğŸ‡ PTæœåŠ¡
    type: select
    proxies:
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸ¡ å®¶å®½èŠ‚ç‚¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº

  - name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯
    type: select
    proxies:
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº

  - name: ğŸ“¢ è°·æ­ŒFCM
    type: select
    proxies:
      - ğŸ’¬ AIèŠ‚ç‚¹
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
  - name: â“‚ï¸ å¾®è½¯Bing
    type: select
    proxies:
      - ğŸ’¬ AIèŠ‚ç‚¹
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
  - name: â“‚ï¸ å¾®è½¯äº‘ç›˜
    type: select
    proxies:
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
  - name: ğŸ“¹ æ²¹ç®¡è§†é¢‘
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨ä¼˜é€‰
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ¥ å¥ˆé£è§†é¢‘
    type: select
    proxies:
      - ğŸ¥ å¥ˆé£èŠ‚ç‚¹
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
  - name: ğŸ“º å“”å“©å“”å“©
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸš€ ä¸‡é‡‘æ²¹
      - â™»ï¸ è‡ªåŠ¨ä¼˜é€‰
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - name: ğŸ® æ¸¸æˆå¹³å°
    type: select
    proxies:
      - ğŸ® æ¸¸æˆèŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨ä¼˜é€‰
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ¡ å®¶å®½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº
      - DIRECT
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸƒ åº”ç”¨å‡€åŒ–
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - DIRECT
      - ğŸš€ ä¸‡é‡‘æ²¹
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸŒ å…¶ä»–åœ°åŒº

  # åŸå§‹ç­–ç•¥ç»„
  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    include-all: true
    exclude-type: direct
  - name: â™»ï¸ è‡ªåŠ¨ä¼˜é€‰
    type: url-test
    include-all: true
    exclude-type: direct
    tolerance: 50
  - name: ğŸ¡ å®¶å®½èŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)å®¶å®½|å®¶åº­|ä½å®…|åŸç”Ÿ'
  - name: ğŸ® æ¸¸æˆèŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)æ¸¸æˆ'
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong'
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan'
  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|Singapur'
  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States'
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)å°æ¹¾|TW|taiwan|å°æ¹¾åœ°åŒº|Taiwan|å°|å°åŒ—|è‡ºç£'
  - name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“å›½|éŸ©å›½èŠ‚ç‚¹'
  - name: ğŸŒ å…¶ä»–åœ°åŒº
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*'
  - name: ğŸ¥ å¥ˆé£èŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)NF|å¥ˆé£|è§£é”|Netflix|NETFLIX|Media'
  - name: ğŸ’¬ AIèŠ‚ç‚¹
    type: select
    include-all: true
    exclude-type: direct
    filter: '(?i)ç¾å›½|æ³°å›½ Vip2|è²å¾‹å®¾ Vip2|éŸ©å›½ Vip2|éŸ©å›½ IPLC æ¸¸æˆ Vip3 Zx|æ–°åŠ å¡ Vip2|æ–°åŠ å¡ IPLC æ¸¸æˆ Vip3 Zx 02|æ–°åŠ å¡ IPLC æ¸¸æˆ Vip3 Zx 06|å°æ¹¾ Vip2'


rules:
  # è‡ªå®šä¹‰è§„åˆ™é›†
  - RULE-SET,direct,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ai,ğŸ¤– AIå¹³å°
  - RULE-SET,talkatone,ğŸ“± Talkatone
  - RULE-SET,card,ğŸ˜ è™šæ‹Ÿå¡æœåŠ¡
  - RULE-SET,school,ã‰† å­¦æ ¡æœåŠ¡
  - RULE-SET,pt,ğŸ‡ PTæœåŠ¡
  - RULE-SET,proxy,ğŸš€ ä¸‡é‡‘æ²¹
  - RULE-SET,localarea,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,unban,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,banad,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,banprogramad,ğŸƒ åº”ç”¨å‡€åŒ–
  - RULE-SET,googlefcm,ğŸ“¢ è°·æ­ŒFCM
  - RULE-SET,googlecn,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,steamcn,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ai-acl,ğŸ¤– AIå¹³å°
  - RULE-SET,openai,ğŸ¤– AIå¹³å°
  - RULE-SET,bing,â“‚ï¸ å¾®è½¯Bing
  - RULE-SET,onedrive,â“‚ï¸ å¾®è½¯äº‘ç›˜
  - RULE-SET,microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,youtube,ğŸ“¹ æ²¹ç®¡è§†é¢‘
  - RULE-SET,netflix,ğŸ¥ å¥ˆé£è§†é¢‘
  - RULE-SET,bilibiliHMT,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,bilibili,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,chinamedia,ğŸŒ å›½å†…åª’ä½“
  - RULE-SET,proxymedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,epic,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,origin,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,sony,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,steam,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,nintendo,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,proxygfwlist,ğŸš€ ä¸‡é‡‘æ²¹
  - RULE-SET,chinadomain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,chinacompanyip,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,download,ğŸ¯ å…¨çƒç›´è¿
  - GEOSITE,CN,ğŸ¯ å…¨çƒç›´è¿
  - GEOSITE,geolocation-!cn,ğŸš€ ä¸‡é‡‘æ²¹
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

rule-providers:
  direct:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/WanderingSoul49/myclash/refs/heads/main/ruleset/list/Direct.list"
    path: ./ruleset/direct.list
    interval: 86400
    format: text

  ai:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/WanderingSoul49/myclash/refs/heads/main/ruleset/list/AI.list"
    path: ./ruleset/ai.list
    interval: 86400
    format: text

  talkatone:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/WanderingSoul49/myclash/refs/heads/main/ruleset/list/Talkatone.list"
    path: ./ruleset/talkatone.list
    interval: 86400
    format: text

  card:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/WanderingSoul49/myclash/refs/heads/main/ruleset/list/Card.list"
    path: ./ruleset/card.list
    interval: 86400
    format: text

  school:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/WanderingSoul49/myclash/refs/heads/main/ruleset/list/School.list"
    path: ./ruleset/school.list
    interval: 86400
    format: text

  pt:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/WanderingSoul49/myclash/refs/heads/main/ruleset/list/PT.list"
    path: ./ruleset/pt.list
    interval: 86400
    format: text

  proxy:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/WanderingSoul49/myclash/refs/heads/main/ruleset/list/Proxy.list"
    path: ./ruleset/proxy.list
    interval: 86400
    format: text

  localarea:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
    path: ./ruleset/localarea.list
    interval: 86400

  unban:
    type: http
    format: text
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"
    path: ./ruleset/unban.list
    interval: 86400

  banad:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"
    path: ./ruleset/banad.list
    interval: 86400

  banprogramad:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"
    path: ./ruleset/banprogramad.list
    interval: 86400

  googlefcm:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"
    path: ./ruleset/googlefcm.list
    interval: 86400

  googlecn:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
    path: ./ruleset/googlecn.list
    interval: 86400

  steamcn:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"
    path: ./ruleset/steamcn.list
    interval: 86400

  ai-acl:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list"
    path: ./ruleset/ai-acl.list
    interval: 86400

  openai:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"
    path: ./ruleset/openai.list
    interval: 86400

  bing:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list"
    path: ./ruleset/bing.list
    interval: 86400

  onedrive:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"
    path: ./ruleset/onedrive.list
    interval: 86400

  microsoft:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
    path: ./ruleset/microsoft.list
    interval: 86400

  apple:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
    path: ./ruleset/apple.list
    interval: 86400

  telegram:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"
    path: ./ruleset/telegram.list
    interval: 86400

  youtube:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"
    path: ./ruleset/youtube.list
    interval: 86400

  netflix:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"
    path: ./ruleset/netflix.list
    interval: 86400

  bilibiliHMT:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"
    path: ./ruleset/bilibiliHMT.list
    interval: 86400

  bilibili:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"
    path: ./ruleset/bilibili.list
    interval: 86400

  chinamedia:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
    path: ./ruleset/chinamedia.list
    interval: 86400

  proxymedia:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"
    path: ./ruleset/proxymedia.list
    interval: 86400

  epic:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"
    path: ./ruleset/epic.list
    interval: 86400

  origin:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list"
    path: ./ruleset/origin.list
    interval: 86400

  sony:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"
    path: ./ruleset/sony.list
    interval: 86400

  steam:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"
    path: ./ruleset/steam.list
    interval: 86400

  nintendo:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list"
    path: ./ruleset/nintendo.list
    interval: 86400

  proxygfwlist:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
    path: ./ruleset/proxygfwlist.list
    interval: 86400

  chinadomain:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
    path: ./ruleset/chinadomain.list
    interval: 86400

  chinacompanyip:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
    path: ./ruleset/chinacompanyip.list
    interval: 86400

  download:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"
    path: ./ruleset/download.list
    interval: 86400
